englercj/resource-loader

src/Resource.js

Because the success status of an XHR request can be 0 when loading local files, loading never finished when using pixi in a cordova app.  I’ve updated the logic, which checks the status and also the length of the response is checked, to make sure a valid response was found.

Fix when using Cordova, which uses file:// to load resources

---

package.json

Hi,
Is it fine if we install testem as a devDep?
Like this we don't have to install it globally to run the tests :)
Thanks

Set testem as a devDep

---

src/Resource.js

Hi,
Since 814607053688eed3f44a26e6116fad8ce42f2197 the module uses `url` as a dependency, which cause an issue since `url` returns `null` when the `port` is not defined. Whereas `window.location.port` returns an empty string `''`. (https://github.com/englercj/resource-loader/blob/fb943287ccdd66a2c7055b0796b9d605b2f30874/src/Resource.js#L556)
The module used `anonymous` even if the resources were on the same server, which trigger a 401 error on my current project (it worked correctly with the previous version).
Thanks

Fix crossOrigin for resources on same server

---

src/Resource.js

This ended up as a CocoonJS support fix. Since its Canvas+ runtime can't create new source elements (!!!), I ended up defaulting to the first URL provided. Maybe this could all be migrated to feature detection, e.g. [canPlayType checks](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/audio.js).

add support for audio loading in CocoonJS Canvas+; fixes #18

---

src/middlewares/caching/memory.js

You should call _next();_ no matter if asset was cached or not.

Fixed: loading gets stuck after getting first asset from cache

---

package.json
src/Resource.js

Required for pixi-compressed-textures
```
var loader = new PIXI.loaders.Loader();
loader.before( PIXI.compressedTextures.extensionChooser(renderer) );
// use @2x texture if resolution is 2, use dds format if its windows
var textureOptions1 = { metadata: { ext: ["@2x.png", ".dds", "@2x.dds"] } };
// use dds format if its windows but dont care for retina
var textureOptions2 = { metadata: { ext: [".dds"] } };
var atlasOptions = { metadata: { imageMeta: textureOptions.extra } }
var stage = new PIXI.Container();
loader.add('building1', 'img/building1.png', textureOptions1)
.add('building2', 'img/building2.png', textureOptions2)
.add('IHateAtlases', 'img/atlas1.json', atlasOptions)
```

Add extra field in Resource for middleware

---

src/Loader.js

#46 We have changed the order when load has finished.
We weren't able te run the tests
https://github.com/englercj/resource-loader/blob/master/test/unit/Resource.test.js#L32
There was a failed test due to an null value where it should be undefined.
```javascript
expect(res).to.have.property('crossOrigin', null);
```

moved complete after error or load

---

src/Loader.js

Fixed a rare crash when an empty string is used in loader. Empty string doesn't make much sense, but it's better to return "not found" rather than crashing.

- fixed crash when parsedUrl.pathname is null (url is empty)

---

src/Resource.js

This PR allows PIXI to load files with a upper case extension in order to solve http://www.html5gamedevs.com/topic/19026-jpg-image-not-working/
In my use case, I'd like to show images uploaded by users without renaming them. Actually, some users upload files with a upper case extension (e.g. .JPG).

Support upper case extension.

---

src/middlewares/parsing/blob.js

Safer way to prevent any unintentional conflict with other library

Use private scope instead of replacing global object

---

src/Loader.js

I'm using the progress property to update a progress bar, the bar was hanging at 100%. All downloads had completed, but my last middleware function was still executing.
Middleware functions may be long running, do not increment the progress or emit the progress event until the middleware has been executed.

Increment progress AFTER middleware execution

---

src/Loader.js

Hello,
The loading state currently is not updated when the load starts / ends, only when the loader is reset.

update loading state

---

src/Loader.js
src/Resource.js
src/middlewares/caching/memory.js
test/fixtures/data.js
test/unit/Loader.test.js
test/unit/Resource.test.js
testem.json

Alternative to #61, a bit more robust checks in different places and includes a small refactor of running middleware.
New behavior of `pre` middleware:
-  Each is called in sequence
- If any middleware calls `complete()` execution of middleware stops and the resource's `load()` is called
- If the resource is complete at the time of calling `load()` it exits
- If `complete()` is called more than once an error is thrown.
Also adds some additional tests and moves some data into a fixture file.

Fix #57 - Proper handling of 'before' middleware

---

package.json

The current version ```1.6.7``` seems to come without the "src" or "dist" folder when fetched from npm:
```sh
~/w/pixi-packer-parser (master) $ rm -rf node_modules/resource-loader/
~/w/pixi-packer-parser (master) $ npm install
resource-loader@1.6.7 node_modules/resource-loader
├── eventemitter3@1.2.0
└── async@2.0.1 (lodash@4.14.0)
~/w/pixi-packer-parser (master) $ ls node_modules/resource-loader/
LICENSE      README.md    node_modules package.json
```
I've looked through the recent changes and I feel like this should fix it - It's one of those things very hard to test without actually doing it though :(

Fix the issue with npm publish not including those folders

---

src/Resource.js

This PR exposes the file/url extension to be a publicly accessible property of Resource. Currently, the only way to get the extension is by calling the private method `_getExtension()`.
I needed this so that it's easier to compare against the extension when creating custom middleware:
```js
function middleware(resource, next) {
if (resource.data && resource.extension === 'blah') {
// do something
}
next();
}

Expose the extension publicly

---

src/Loader.js
test/unit/Loader.test.js

A situation can arise when there's 2 resources being loaded with the second one being a sprite-sheet. Sprite-sheets require an `after` middleware to add extra files to be loaded (the sprite-sheet image itself)
If the call to `dequeue` happens on the sprite-sheet resource and the `_onLoad` of the previous resource is on the queue, then the `_onLoad` is resumed. The `after` middleware will be run the first resource and when it is spliced out of `_resourcesParsing` in the `async.eachSeries` completion callback the sprite-sheet resource will not be in `_resourcesParsing`. `_resourcesParsing` is now empty and `_onComplete` is called. The `after` middleware is not run before on the sprite-sheet and thus it hasn't loaded its associated texture
If you have code relying on the texture to be loaded …

Moved dequeue to after push to _resourcesParsing

---

src/Loader.js

Async docs for [QueueObject](https://caolan.github.io/async/docs.html#QueueObject) indicates that `concurrency` can be altered on-the-fly. This would provide some flexibility in adjusting this amount after Loader has been created, e.g., `PIXI.loader`.
@funkypaul reported this issue to me while trying to reduce the concurrency load for IE 11. While a solution which directly fixes this issue would be better, I still think there's value in adding a `concurrency` member.

Adds the ability to change concurrency on-the-fly

---

jsdoc.conf.json
package.json

Replaces jaguarjs-jsdoc template with @pixi/jsdoc-template. Adds support for mobile docs
**Preview**
http://mattkarl.com/resource-loader/Resource.html

Replaces Jaguar template with Pixi template

---

src/Loader.js
src/Resource.js
test/unit/Loader.test.js
test/unit/Resource.test.js

This is related to cumulative precision error that in some cases might exceed 100.
It depends on number of chunks that own distributed progress parts.
Trivial example in JS:
```javascript
// for console
c = i = 6, t = 0; while (i-- > 0) t += 100/c; t
100.00000000000001
// OR more readable
const total = 29;
let progress = 0;
let i = total;
while (i > 0) {
progress += 100/total;
i--;
}
console.log(progress === 100.00000000000004); // true
```

progress cumulative precision error

---

src/Resource.js
test/unit/Resource.test.js

Fixes #119 
Adds a test for the new behaviour and fixes the behaviour in the case where `window.origin` is `null`.
Test passed locally (although the event tests of the Loader failed on my machine, but I don't see how anything I changed might have caused that so, assuming it will work on Travis!)

Add test and fix for iframe sandbox cross origin behaviour.

---

src/Resource.js
test/unit/Resource.test.js

Set window.origin to string in test.
Do a more rigorous check for window.origin not matching window.location.origin.
#120 attempted to implement this check, but was operating under a flawed assumption. This PR rectifies that!

Actually check for sandboxed iframe.

---

src/Resource.ts

Unfortunately no ways to use webm videos on iOS and no perspectives that it should works in near future. It needs fallback video encoded using HEVC codec in mov container. That's a main reason why we need mov files support here.

Add *.mov video files support
